# -*- mode: ruby -*-
# vi: set ft=ruby :

unless Vagrant.has_plugin?("vagrant-vbguest")
  puts 'Installing vagrant-vbguest Plugin...'
  system('vagrant plugin install vagrant-vbguest')
end

# Create local Directory for sharing with VM
FileUtils.mkdir_p './cnv'

Vagrant.configure("2") do |config|

  config.ssh.insert_key = false
  config.ssh.forward_agent = true
  config.ssh.forward_x11 = true
  config.vbguest.auto_update = true
  config.vm.box_check_update = false


  # CNV Labs
  config.vm.define "cnvlab" do |lab|
    lab.vm.hostname = "cnvlab"
    lab.vm.network :private_network, type: "dhcp"
    lab.vm.box = "ubuntu/bionic64" # Ubuntu 18.04 LTS
    lab.vm.provider "virtualbox" do |vb|
      vb.name = "cnvlab"
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.memory = "1024"
      vb.cpus = 1
    end #of vb
    # Shared forlders
    if Vagrant::Util::Platform.windows? then
      lab.vm.synced_folder "cnv-shared", "/home/vagrant/cnv-shared",
        id: "shared", owner: "vagrant", group: "vagrant",
        mount_options: ["dmode=775","fmode=664"]
    else
      lab.vm.synced_folder "cnv-shared", "/home/vagrant/cnv-shared",
      mount_options: ["dmode=775","fmode=664"]
    end # of shared folders
    # Provision VM
    lab.vm.provision :shell, path: "cnv-provision.sh"

  end # of lab config

end # of config
